### ISSUE TITLE
Office Center crashes Cinnamon

### ISSUE THREAD

**Issue by mfreeman72** [collinss/cinnamon-office-center#1]
This is a continuation of our discussion on the Cinnamon Applets site regarding this applet causing Cinnamon to crash to the fallback session when added to the panel. You had asked me to send you the logs. I apologize for my noobness here (been on Linux for a long time, but Cinnamon for just a few months, and rarely have I ever had to deal with logs, so...). Could you tell me exactly which logs you need and where they would be found?

**Comment by collinss** [comment]
I'm not sure what logs to ask for since they apparently tend to vary based on your distribution, but offhand, `~/.xsession-errors` would be a useful one if you have it (if you are using Mint, you should). Otherwise you would have to figure out what logs your distribution uses, and where they are.

**Comment by mfreeman72** [comment]
Ok, first off, my system is running Linux Mint 17 Cinnamon 64-bit.

Now, I don't see how to attach non-image files here, so I'll just cut-paste the section of .xsession-errors that refers to your addon:

```
JS ERROR: !!!   Exception was: Gio.IOErrorEnum: Too many open files
JS ERROR: !!!     message = '"Too many open files"'
JS ERROR: !!!     fileName = '"/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js"'
JS ERROR: !!!     lineNumber = '550'
JS ERROR: !!!     stack = '"0 anonymous("dir" = [object _private_unknown_GLocalFile])@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:550
```

1 anonymous("dir" = [object _private_unknown_GLocalFile])@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:557
2 anonymous([object _private_unknown_GInotifyDirectoryMonitor], [object _private_unknown_GLocalFile], null, 0)@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:538
"'
    JS ERROR: !!!   Exception was: Gio.IOErrorEnum: Too many open files
    JS ERROR: !!!     message = '"Too many open files"'
    JS ERROR: !!!     fileName = '"/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js"'
    JS ERROR: !!!     lineNumber = '550'
    JS ERROR: !!!     stack = '"0 anonymous("dir" = [object _private_unknown_GLocalFile])@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:550
1 anonymous([object _private_unknown_GInotifyDirectoryMonitor], [object _private_unknown_GLocalFile], null, 0)@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:538
"'
    JS ERROR: !!!   Exception was: Gio.IOErrorEnum: Too many open files
    JS ERROR: !!!     message = '"Too many open files"'
    JS ERROR: !!!     fileName = '"/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js"'
    JS ERROR: !!!     lineNumber = '550'
    JS ERROR: !!!     stack = '"0 anonymous("dir" = [object _private_unknown_GLocalFile])@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:550
1 anonymous([object _private_unknown_GInotifyDirectoryMonitor], [object _private_unknown_GLocalFile], null, 1)@/home/mike/.local/share/cinnamon/applets/officeCenter@scollins/applet.js:538
"'

**Comment by collinss** [comment]
That's helpful. Do you have the option "Include subfolders" selected in the settings? If so, then try unselecting it and let me know if that helps.

**Comment by mfreeman72** [comment]
Yes. Turning off "Include subfolders" keeps it from crashing.

**Comment by collinss** [comment]
Good, that means that it should be easier to fix.

**Comment by mfreeman72** [comment]
Ah! I also discovered that it is looking into my Home folder instead of my Documents folder. Since I have a link to my Documents folder on my desktop, could it be getting tripped up when it gets the file list from ~/Desktop/Documents and finds it the same as ~/Documents?

**Comment by collinss** [comment]
The logs said the problem is that it's trying to open too many files at once. Having it point to your home folder could explain why there are so many, and why I've never seen this problem before. I should be able to fix it so that it doesn't do that in the future, though, and it may also improve performance as well.

**Comment by mfreeman72** [comment]
Terrific! Until then, I'll just avoid that subfolder option. Thanks for your help!

**Comment by collinss** [comment]
I just uploaded a new version. If you could try it out and see if it still causes problems, I would appreciate it.

**Comment by mfreeman72** [comment]
Well, I don't know if it's a problem, or that I just have a huge number of documents in my subfolders (this computer has 7+ years worth of documents, pictures, etc. in the Documents folder). But, I upgraded to this newest version, turned on the subfolders option, and it didn't crash. However, Cinnamon became unresponsive as it apparently searched my subfolders for over 5 minutes before I just forced a logout. I tried logging back in, and I never got to the desktop no matter how long I let it go. I had to install another DE to get to a usable desktop, run cinnamon-settings, get to the applet configuration, and turn off the subfolders option.

**Comment by collinss** [comment]
Hmm... sorry about that. I'm not sure if there is a better way to do this, but I'll see if I can find something. In the mean time maybe I'll have to include a warning about the dangers of using that feature with a large number of files. Also, for future reference, if you can't load a DE you can change the settings by logging into a command prompt and editing `~/.configs/applet_id/applet_id.json`.
